---
title: "Do FIN embryos express Nipbl at lower levels than Flox embryos?"
output: html_notebook
---

Load libraries.
```{r}
library(tidyverse)
library(ggsignif)
library(Rmisc)
library(scales)
```

Load norm umi per embryo.
```{r}
load("/Volumes/all_ssd/20220414-seurat/norm-umi-per-embryo.Robj")
norm.umi[18, "cre"] <- 0
```

Calculate error for cre, bgeo, and nipbl.
```{r}
error.cre <- summarySE(data = norm.umi, measurevar = "cre", groupvars = c("genotype"))
error.bgeo <- summarySE(data = norm.umi, measurevar = "bGeo", groupvars = c("genotype"))
error.nipbl <- summarySE(data = norm.umi, measurevar = "Nipbl", groupvars = c("genotype"))
```

Perform t test for cre, bgeo, and nipbl.
```{r}
t.test(formula = log10(norm.umi$cre) ~ norm.umi$genotype, alternative = "two.sided", paired = FALSE, conf.level = 0.95)
```

```{r}
t.test(formula = log10(norm.umi$bGeo) ~ norm.umi$genotype, alternative = "two.sided", paired = FALSE, conf.level = 0.95)
```

```{r}
t.test(formula = log10(norm.umi$Nipbl) ~ norm.umi$genotype, alternative = "two.sided", paired = FALSE, conf.level = 0.95)
```

```{r}
cre.plot <- ggplot() +
  geom_jitter(data = norm.umi, mapping = aes(x = genotype, y = cre, group = genotype), width = 0.1, size = 0.5) +
  geom_point(data = error.cre, mapping = aes(x = genotype, y = cre, color = genotype, group = genotype), position = position_nudge(x = 0.15), size = 1) +
  geom_errorbar(data = error.cre, mapping = aes(x = genotype, ymin = cre-ci, ymax = cre+ci, color = genotype, group = genotype), width = 0.05, position = position_nudge(x = 0.15)) +
  scale_color_manual(values = c("blue", "red"), labels = c("Nipbl Flox/+", "Nipbl FIN/+")) + 
#  geom_signif(data = norm.umi %>% filter(stage == "CC"), mapping = aes(x = genotype, y = Nipbl, group = genotype), xmin = 1.15, xmax = 2.15, y_position = 3.05, annotation = "***", size = 0.33, textsize = 3.5) +
  scale_x_discrete(labels = c("Nipbl Flox/+\nN = 12", "Nipbl FIN/+\nN = 14")) +
#  scale_y_log10(breaks=trans_breaks('log10', function(x) 10^x), labels=trans_format('log10', math_format(10^.x))) +
  labs(title = "Cre", x = "Genotype", y = "Norm Transcripts Per Embryo", color = "95% CI Mean", tag = "A") +
  theme_classic(base_size = 7) +
  theme(plot.title = element_text(hjust = 0.5), legend.key.height = unit(7, "pt"), plot.tag = element_text(size = 9, face = "bold"), legend.position = "right")

cre.plot

ggsave(plot = cre.plot, filename = "cre-plot.png", device = "png", width = 3.25, height = 2.25)
```

```{r}
bGeo.plot <- ggplot() +
  geom_jitter(data = norm.umi, mapping = aes(x = genotype, y = bGeo, group = genotype), width = 0.1, size = 0.5) +
  geom_point(data = error.bgeo, mapping = aes(x = genotype, y = bGeo, color = genotype, group = genotype), position = position_nudge(x = 0.15), size = 1) +
  geom_errorbar(data = error.bgeo, mapping = aes(x = genotype, ymin = bGeo-ci, ymax = bGeo+ci, color = genotype, group = genotype), width = 0.05, position = position_nudge(x = 0.15)) +
  scale_color_manual(values = c("blue", "red"), labels = c("Nipbl Flox/+", "Nipbl FIN/+")) + 
#  geom_signif(data = norm.umi %>% filter(stage == "CC"), mapping = aes(x = genotype, y = Nipbl, group = genotype), xmin = 1.15, xmax = 2.15, y_position = 3.05, annotation = "***", size = 0.33, textsize = 3.5) +
  scale_x_discrete(labels = c("Nipbl Flox/+\nN = 12", "Nipbl FIN/+\nN = 14")) +
#  scale_y_log10(breaks=trans_breaks('log10', function(x) 10^x), labels=trans_format('log10', math_format(10^.x))) +
  labs(title = "Bgeo", x = "Genotype", y = "Norm Transcripts Per Embryo", color = "95% CI Mean", tag = "B") +
  theme_classic(base_size = 7) +
  theme(plot.title = element_text(hjust = 0.5), legend.key.height = unit(7, "pt"), plot.tag = element_text(size = 9, face = "bold"), legend.position = "right")

bGeo.plot

ggsave(plot = bGeo.plot, filename = "Bgeo-plot.png", device = "png", width = 3.25, height = 2.25)
```

```{r}
nipbl.plot <- ggplot() +
  geom_jitter(data = norm.umi, mapping = aes(x = genotype, y = Nipbl, group = genotype), width = 0.1, size = 0.5) +
  geom_point(data = error.nipbl, mapping = aes(x = genotype, y = Nipbl, color = genotype, group = genotype), position = position_nudge(x = 0.15), size = 1) +
  geom_errorbar(data = error.nipbl, mapping = aes(x = genotype, ymin = Nipbl-ci, ymax = Nipbl+ci, color = genotype, group = genotype), width = 0.05, position = position_nudge(x = 0.15)) +
  scale_color_manual(values = c("blue", "red"), labels = c("Nipbl Flox/+", "Nipbl FIN/+")) + 
  geom_signif(data = norm.umi, mapping = aes(x = genotype, y = Nipbl, group = genotype), xmin = 1.15, xmax = 2.15, y_position = 1000, annotation = "P=6.277e-10", size = 0.33, textsize = 2.3) +
  scale_x_discrete(labels = c("Nipbl Flox/+\nN = 12", "Nipbl FIN/+\nN = 14")) +
  scale_y_continuous(limits = c(200, 1100)) +
  labs(title = "Nipbl", x = "Genotype", y = "Norm Transcripts Per Embryo", color = "95% CI Mean", tag = "C") +
  theme_classic(base_size = 7) +
  theme(plot.title = element_text(hjust = 0.5), legend.key.height = unit(7, "pt"), plot.tag = element_text(size = 9, face = "bold"), legend.position = "right")

nipbl.plot

ggsave(plot = nipbl.plot, filename = "nipbl-plot.png", device = "png", width = 3.25, height = 2.25)
```

