---
title: "Plot UMAP"
output: html_notebook
---

Download UMAP.
```{bash}
scp schea2@hpc3.rcic.uci.edu:/share/crsp/lab/alcalof/schea2/20220414-seurat/umap-by-embryo-all-aggr.Robj .
```

Load libraries.
```{r}
library(tidyverse)
library(scales)
```

Load UMAP.
```{r}
load("/Volumes/all_ssd/20220414-seurat/umap-by-embryo-all-aggr.Robj")
```

Plot UMAP by stage.
```{r}
stage.umap <- ggplot() +
  geom_point(data = sample(whole.umap), mapping = aes(x = umap.1, y = umap.2, color = stage), shape = 20, stroke = 0, size = 0.5) +
  labs(x = "UMAP 1", y = "UMAP 2", color = "Stage") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"))

stage.umap

ggsave(plot = stage.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-by-stage-all-aggr.png", device = "png", width = 3.25, height = 2.25)
```

Plot UMAP by genotype.
```{r}
stage.umap <- ggplot() +
  geom_point(data = whole.umap, mapping = aes(x = umap.1, y = umap.2, color = stage), shape = 20, stroke = 0, size = 0.5) +
  facet_wrap(~stage, nrow = 1) +
  labs(x = "UMAP 1", y = "UMAP 2", color = "Genotype") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"), strip.background = element_blank())

stage.umap

ggsave(plot = stage.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-facet-stage-all-aggr.png", device = "png", width = 6.5, height = 2.25)
```

Plot UMAP by genotype.
```{r}
genotype.umap <- ggplot() +
  geom_point(data = sample(whole.umap %>% filter(stage == "LB")), mapping = aes(x = umap.1, y = umap.2, color = genotype), shape = 20, stroke = 0, size = 0.5) +
  scale_color_manual(values = c("royalblue", "indianred")) +
  labs(title = "Late Bud", x = "UMAP 1", y = "UMAP 2", color = "Genotype") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"))

genotype.umap

ggsave(plot = genotype.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-by-genotype-late-bud-all-aggr.png", device = "png", width = 3.25, height = 2.25)
```

Plot UMAP by genotype.
```{r}
genotype.umap <- ggplot() +
  geom_point(data = sample(whole.umap %>% filter(stage == "LB")), mapping = aes(x = umap.1, y = umap.2, color = genotype), shape = 20, stroke = 0, size = 0.5) +
  facet_wrap(~genotype, nrow = 1) +
  scale_color_manual(values = c("royalblue", "indianred")) +
  labs(title = "Late Bud", x = "UMAP 1", y = "UMAP 2", color = "Genotype") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"), strip.background = element_blank())

genotype.umap

ggsave(plot = genotype.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-facet-genotype-late-bud-all-aggr.png", device = "png", width = 6.5, height = 2.25)
```

Plot UMAP by embryo.
```{r}
embryo.umap <- ggplot() +
  geom_point(data = sample(whole.umap %>% filter(stage == "LB") %>% filter(genotype == "Nipbl Flox/+")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
  scale_color_manual(values = hue_pal()(28)[c(1, 15, 3, 17, 5)]) +
  labs(title = "Nipbl Flox/+, Late Bud", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"))

embryo.umap

ggsave(plot = embryo.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-by-embryo-flox-late-bud-all-aggr.png", device = "png", width = 3.25, height = 2.25)
```

Plot UMAP by embryo.
```{r}
embryo.umap <- ggplot() +
  geom_point(data = sample(whole.umap %>% filter(stage == "LB") %>% filter(genotype == "Nipbl Flox/+")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
  facet_wrap(~embryo, ncol = 4) +
  scale_color_manual(values = hue_pal()(28)[c(1, 15, 3, 17, 5)]) +
  labs(title = "Nipbl Flox/+, Late Bud", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"), strip.background = element_blank())

embryo.umap

ggsave(plot = embryo.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-facet-embryo-flox-late-bud-all-aggr.png", device = "png", width = 6.5, height = 3.6)
```

Plot UMAP by embryo.
```{r}
embryo.umap <- ggplot() +
  geom_point(data = sample(whole.umap %>% filter(stage == "LB") %>% filter(genotype == "Nipbl FIN/+")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
  scale_color_manual(values = hue_pal()(28)[c(19, 7, 21, 9, 23, 11)]) +
  labs(title = "Nipbl FIN/+, Late Bud", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"))

embryo.umap

ggsave(plot = embryo.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-by-embryo-fin-late-bud-all-aggr.png", device = "png", width = 3.25, height = 2.25)
```

Plot UMAP by embryo.
```{r}
embryo.umap <- ggplot() +
  geom_point(data = sample(whole.umap %>% filter(stage == "LB") %>% filter(genotype == "Nipbl FIN/+")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
  facet_wrap(~embryo, ncol = 4) +
  scale_color_manual(values = hue_pal()(28)[c(19, 7, 21, 9, 23, 11)]) +
  labs(title = "Nipbl FIN/+, Late Bud", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"), strip.background = element_blank())

embryo.umap

ggsave(plot = embryo.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-facet-embryo-fin-late-bud-all-aggr.png", device = "png", width = 6.5, height = 3.6)
```

Plot UMAP by genotype.
```{r}
genotype.umap <- ggplot() +
  geom_point(data = sample(whole.umap %>% filter(stage == "CC")), mapping = aes(x = umap.1, y = umap.2, color = genotype), shape = 20, stroke = 0, size = 0.5) +
  scale_color_manual(values = c("royalblue", "indianred")) +
  labs(title = "Cardiac Crescent", x = "UMAP 1", y = "UMAP 2", color = "Genotype") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"))

genotype.umap

ggsave(plot = genotype.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-by-genotype-cardiac-crescent-all-aggr.png", device = "png", width = 3.25, height = 2.25)
```

Plot UMAP by genotype.
```{r}
genotype.umap <- ggplot() +
  geom_point(data = sample(whole.umap %>% filter(stage == "CC")), mapping = aes(x = umap.1, y = umap.2, color = genotype), shape = 20, stroke = 0, size = 0.5) +
  facet_wrap(~genotype, ncol = 2) +
  scale_color_manual(values = c("royalblue", "indianred")) +
  labs(title = "Cardiac Crescent", x = "UMAP 1", y = "UMAP 2", color = "Genotype") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"), strip.background = element_blank())

genotype.umap

ggsave(plot = genotype.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-facet-genotype-cardiac-crescent-all-aggr.png", device = "png", width = 6.5, height = 2.25)
```

Plot UMAP by embryo.
```{r}
embryo.umap <- ggplot() +
  geom_point(data = sample(whole.umap %>% filter(stage == "CC") %>% filter(genotype == "Nipbl Flox/+")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
  scale_color_manual(values = hue_pal()(28)[c(25, 13, 27, 2, 16, 4, 18, 6)]) +
  labs(title = "Nipbl Flox/+, Cardiac Crescent", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"))

embryo.umap

ggsave(plot = embryo.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-by-embryo-flox-cardiac-crescent-all-aggr.png", device = "png", width = 3.25, height = 2.25)
```

Plot UMAP by embryo.
```{r}
embryo.umap <- ggplot() +
  geom_point(data = sample(whole.umap %>% filter(stage == "CC") %>% filter(genotype == "Nipbl Flox/+")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
  facet_wrap(~embryo, ncol = 4) +
  scale_color_manual(values = hue_pal()(28)[c(25, 13, 27, 2, 16, 4, 18, 6)]) +
  labs(title = "Nipbl Flox/+, Cardiac Crescent", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"), strip.background = element_blank())

embryo.umap

ggsave(plot = embryo.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-facet-embryo-flox-cardiac-crescent-all-aggr.png", device = "png", width = 6.5, height = 3.6)
```

Plot UMAP by embryo.
```{r}
embryo.umap <- ggplot() +
  geom_point(data = sample(whole.umap %>% filter(stage == "CC") %>% filter(genotype == "Nipbl FIN/+")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
  scale_color_manual(values = hue_pal()(28)[c(20, 8, 22, 10, 24, 12, 26, 14)]) +
  labs(title = "Nipbl FIN/+, Cardiac Crescent", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"))

embryo.umap

ggsave(plot = embryo.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-by-embryo-fin-cardiac-crescent-all-aggr.png", device = "png", width = 3.25, height = 2.25)
```

Plot UMAP by embryo.
```{r}
embryo.umap <- ggplot() +
  geom_point(data = sample(whole.umap %>% filter(stage == "CC") %>% filter(genotype == "Nipbl FIN/+")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
  facet_wrap(~embryo, ncol = 4) +
  scale_color_manual(values = hue_pal()(28)[c(20, 8, 22, 10, 24, 12, 26, 14)]) +
  labs(title = "Nipbl FIN/+, Cardiac Crescent", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
  guides(color = guide_legend(override.aes = list(size=2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"), strip.background = element_blank())

embryo.umap

ggsave(plot = embryo.umap, filename = "/Volumes/all_ssd/20220414-seurat/umap-facet-embryo-fin-cardiac-crescent-all-aggr.png", device = "png", width = 6.5, height = 3.6)
```