---
title: "Generate UMAPs"
output: html_notebook
---

```{bash}
#scp -r schea2@hpc3.rcic.uci.edu:'/share/crsp/lab/alcalof/schea2/20220414-seurat/flox-integr-res-0.0120/umap*-END.Robj' /Volumes/all_ssd/20220414-seurat/flox-integr-res-0.0120

scp -r schea2@hpc3.rcic.uci.edu:'/share/crsp/lab/alcalof/schea2/20220414-seurat/flox-integr-res-0.0120/umap*-ECT.Robj' /Volumes/all_ssd/20220414-seurat/flox-integr-res-0.0120

#scp -r schea2@hpc3.rcic.uci.edu:'/share/crsp/lab/alcalof/schea2/20220414-seurat/flox-integr-res-0.0120/umap*-MES.Robj' /Volumes/all_ssd/20220414-seurat/flox-integr-res-0.0120
```

```{r}
library(tidyverse)
library(RColorBrewer)
library(scales)
library(patchwork)
```

```{r}
for (i in c("ECT")) {
    
    print("loading umap coordinates across stage and embryo")
    filename.robj <- paste0("/Volumes/all_ssd/20220414-seurat/flox-integr-res-0.0120/umap-by-stage-embryo-flox-", i, ".Robj")
    load(file = filename.robj)

    print("generating umap plots by stage and embryo")

    stage.umap <- ggplot() +
    geom_point(data = sample(clust.umap), mapping = aes(x = umap.1, y = umap.2, color = stage), shape = 20, stroke = 0, size = 0.5) +
        labs(title = "Nipbl Flox/+", x = "UMAP 1", y = "UMAP 2", color = "Stage") +
        guides(color = guide_legend(override.aes = list(size = 2.3))) +
        theme_classic(base_size = 7) +
        theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"))
        
    filename.robj <- paste0("/Volumes/all_ssd/20220414-seurat/flox-integr-res-0.0120/umap-by-stage-flox-", i, ".png")
    ggsave(plot = stage.umap, filename = filename.robj, device = "png", width = 3.5, height = 2.25)

    stage.umap <- ggplot() +
    geom_point(data = sample(clust.umap), mapping = aes(x = umap.1, y = umap.2, color = stage), shape = 20, stroke = 0, size = 0.5) +
        facet_wrap(~stage, ncol = 2) +
        labs(title = "Nipbl Flox/+", x = "UMAP 1", y = "UMAP 2", color = "Stage") +
        guides(color = guide_legend(override.aes = list(size = 2.3))) +
        theme_classic(base_size = 7) +
        theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"), strip.background = element_blank())

    filename.robj <- paste0("/Volumes/all_ssd/20220414-seurat/flox-integr-res-0.0120/umap-facet-stage-flox-", i, ".png")
    ggsave(plot = stage.umap, filename = filename.robj, device = "png", width = 6.5, height = 2.25)

    embryo.umap <- ggplot() +
    geom_point(data = sample(clust.umap %>% filter(stage == "LB")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
        scale_color_manual(values = hue_pal()(28)[c(1, 15, 3, 17, 5)]) +
        labs(title = "Late Bud, Nipbl Flox/+", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
        guides(color = guide_legend(override.aes = list(size = 2.3))) +
        theme_classic(base_size = 7) +
        theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"))

    filename.robj <- paste0("/Volumes/all_ssd/20220414-seurat/flox-integr-res-0.0120/umap-by-embryo-late-bud-flox-", i, ".png")
    ggsave(plot = embryo.umap, filename = filename.robj, device = "png", width = 3.5, height = 2.25)

    embryo.umap <- ggplot() +
    geom_point(data = sample(clust.umap %>% filter(stage == "LB")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
        facet_wrap(~embryo, ncol = 4) +
        scale_color_manual(values = hue_pal()(28)[c(1, 15, 3, 17, 5)]) +
        labs(title = "Late Bud, Nipbl Flox/+", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
        guides(color = guide_legend(override.aes = list(size = 2.3))) +
        theme_classic(base_size = 7) +
        theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"), strip.background = element_blank())

    filename.robj <- paste0("/Volumes/all_ssd/20220414-seurat/flox-integr-res-0.0120/umap-facet-embryo-late-bud-flox-", i, ".png")
    ggsave(plot = embryo.umap, filename = filename.robj, device = "png", width = 6.5, height = 3.6)

    embryo.umap <- ggplot() +
    geom_point(data = sample(clust.umap %>% filter(stage == "CC")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
        scale_color_manual(values = hue_pal()(28)[c(25, 13, 27, 2, 16, 4, 18, 6)]) +
        labs(title = "Cardiac Crescent, Nipbl Flox/+", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
        guides(color = guide_legend(override.aes = list(size = 2.3))) +
        theme_classic(base_size = 7) +
        theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"))

    filename.robj <- paste0("/Volumes/all_ssd/20220414-seurat/flox-integr-res-0.0120/umap-by-embryo-cardiac-crescent-flox-", i, ".png")
    ggsave(plot = embryo.umap, filename = filename.robj, device = "png", width = 3.5, height = 2.25)

    embryo.umap <- ggplot() +
    geom_point(data = sample(clust.umap %>% filter(stage == "CC")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
        facet_wrap(~embryo, ncol = 4) +
        scale_color_manual(values = hue_pal()(28)[c(25, 13, 27, 2, 16, 4, 18, 6)]) +
        labs(title = "Cardiac Crescent, Nipbl Flox/+", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
        guides(color = guide_legend(override.aes = list(size = 2.3))) +
        theme_classic(base_size = 7) +
        theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"), strip.background = element_blank())

    filename.robj <- paste0("/Volumes/all_ssd/20220414-seurat/flox-integr-res-0.0120/umap-facet-embryo-cardiac-crescent-flox-", i, ".png")
    ggsave(plot = embryo.umap, filename = filename.robj, device = "png", width = 6.5, height = 3.6)

}

```


