---
title: "What does the expression of gene markers for each cluster look like?"
output: html_notebook
---

Load libraries.
```{r}
library(Seurat)
library(tidyverse)
library(RColorBrewer)
```

Load FIN cells.
```{r}
load("/Volumes/all_ssd/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-3-projected-flox-3-res-0.025/fin-3-projected-flox-3-res-0.025.Robj")
```

Load markers.
```{r}
load("/Volumes/all_ssd/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-3-projected-flox-3-res-0.025/projected-diff-genes-fin-3-projected-flox-3-res-0.025.Robj")
head(diff.genes)
```

Factor gene.
```{r}
diff.genes$gene <- factor(diff.genes$gene)
head(diff.genes)
```

Grab top genes per cluster. 
```{r}
diff.genes %>% group_by(cluster) %>% slice_head(n = 79/length(levels(diff.genes$cluster))*2)
top.genes <- diff.genes %>% group_by(cluster) %>% slice_head(n = 79/length(levels(diff.genes$cluster))*2) %>% pull(gene)
top.genes
```

Pull expression data for cluster.
```{r}
#grab expression data for each gene
expr.umap <- as.data.frame(t(as.data.frame(fin.clust@assays$SCT_3@data[top.genes,])))

#convert column names
colnames(expr.umap) <- str_replace(top.genes, pattern = "-", replacement = "_")

#add umap embedding and cluster identities
expr.umap <- cbind(expr.umap, fin.clust@reductions$ref.umap@cell.embeddings)

#add names for each gene as cluster identity
top.clusters <- diff.genes %>% group_by(cluster) %>% slice_head(n = 79/length(levels(diff.genes$cluster))*2) %>% pull(cluster)
names(top.clusters) <- colnames(expr.umap)[1:length(top.genes)]

dir.create("/Volumes/all_ssd/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-3-projected-flox-3-res-0.025/feat-plot-fin-3-projected-flox-3-res-0.025")
```

Generate feature plot.
```{r}
loop.count = 0

for (i in colnames(expr.umap)[c(1:113, 115:150, 152:158)]) {
  
loop.count = loop.count + 1

if(loop.count < 10) {
  string.loop.count <- paste0("00", loop.count)
} else if(loop.count >= 10 & loop.count < 100) {
    string.loop.count <- paste0("0", loop.count)
} else if(loop.count >= 100) {
  string.loop.count <- loop.count
}

feat.plot <- ggplot(data = sample(expr.umap), mapping = aes(x = refUMAP_1, y = refUMAP_2)) +
         geom_point(mapping = aes_string(color = i), shape = 20, stroke = 0, size = 0.5) +
        scale_color_gradient(low = "grey", high = "red") +
    labs(title = str_replace(i, pattern = "_", replacement = "-"), subtitle = "Cluster 3, Nipbl FIN/+", x = "UMAP 1", y = "UMAP 2", color = "Norm\nUMI") +
  theme_classic(base_size = 7) +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5), axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), legend.key.size = unit(7, "pt"))

filename.png <- paste0("/Volumes/all_ssd/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-3-projected-flox-3-res-0.025/feat-plot-fin-3-projected-flox-3-res-0.025/", top.clusters[i], "-", string.loop.count, "-", str_replace(i, pattern = "_", replacement = "-"), "-feat-plot-fin-3-projected-flox-3-res-0.025.png")
ggsave(plot = feat.plot, filename = filename.png, device = "png", unit = "in", width = 3.5, height = 2.25)

}
```
