---
title: "R Notebook"
output: html_notebook
---

```{bash}
scp -r schea2@hpc3.rcic.uci.edu:'/share/crsp/lab/alcalof/schea2/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-1-projected-flox-1-res-0.074/fin-1.3-projected-flox-1.3-res-0.056' /Volumes/all_ssd/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-1-projected-flox-1-res-0.074

scp -r schea2@hpc3.rcic.uci.edu:'/share/crsp/lab/alcalof/schea2/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-1-projected-flox-1-res-0.074/fin-1.2-projected-flox-1.2-res-0.104' /Volumes/all_ssd/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-1-projected-flox-1-res-0.074

scp -r schea2@hpc3.rcic.uci.edu:'/share/crsp/lab/alcalof/schea2/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-1-projected-flox-1-res-0.074/fin-1.1-projected-flox-1.1-res-0.177' /Volumes/all_ssd/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-1-projected-flox-1-res-0.074
```

```{r}
library(Seurat)
library(tidyverse)
library(pracma)
library(RColorBrewer)
library(scales)
library(patchwork)
```

```{r}

res <- c("0.056", "0.104", "0.177")
names(res) <- c("1.3", "1.2", "1.1")

for (i in c("1.3", "1.2", "1.1")) {
  
print("setting working directory")
dir.name <- paste0("/Volumes/all_ssd/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-1-projected-flox-1-res-0.074/fin-", i, "-projected-flox-", i, "-res-", res[i])
setwd(dir.name)

print("loading umap coordinates")
filename.robj <- paste0(dir.name, "/projected-umap-by-stage-embryo-cluster-fin-", i, "-projected-flox-", i, "-res-", res[i], ".Robj")
load(file = filename.robj)

print("generating umap plots by stage and embryo")

stage.umap <- ggplot() +
geom_point(data = sample(subclust.umap), mapping = aes(x = umap.1, y = umap.2, color = stage), shape = 20, stroke = 0, size = 0.5) +
    labs(title = "Nipbl FIN/+", x = "UMAP 1", y = "UMAP 2", color = "Stage") +
    guides(color = guide_legend(override.aes = list(size = 2.3))) +
    theme_classic(base_size = 7) +
    theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"))

filename.png <- paste0(dir.name, "/projected-umap-by-stage-fin-", i, "-projected-flox-", i, "-res-", res[i], ".png")
ggsave(plot = stage.umap, filename = filename.png, device = "png", width = 3.5, height = 2.25)

stage.umap <- ggplot() +
geom_point(data = sample(subclust.umap), mapping = aes(x = umap.1, y = umap.2, color = stage), shape = 20, stroke = 0, size = 0.5) +
    facet_wrap(~stage, ncol = 2) +
    labs(title = "Nipbl FIN/+", x = "UMAP 1", y = "UMAP 2", color = "Stage") +
    guides(color = guide_legend(override.aes = list(size = 2.3))) +
    theme_classic(base_size = 7) +
    theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"), strip.background = element_blank())

filename.png <- paste0(dir.name, "/projected-umap-facet-stage-fin-", i, "-projected-flox-", i, "-res-", res[i], ".png")
ggsave(plot = stage.umap, filename = filename.png, device = "png", width = 6.5, height = 2.25)

embryo.umap <- ggplot() +
geom_point(data = sample(subclust.umap %>% filter(stage == "LB")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
    scale_color_manual(values = hue_pal()(28)[c(19, 7, 21, 9, 23, 11)]) +
    labs(title = "Late Bud, Nipbl FIN/+", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
    guides(color = guide_legend(override.aes = list(size = 2.3))) +
    theme_classic(base_size = 7) +
    theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"))

filename.png <- paste0(dir.name, "/projected-umap-by-embryo-late-bud-fin-", i, "-projected-flox-", i, "-res-", res[i], ".png")
ggsave(plot = embryo.umap, filename = filename.png, device = "png", width = 3.5, height = 2.25)

embryo.umap <- ggplot() +
geom_point(data = sample(subclust.umap %>% filter(stage == "LB")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
    facet_wrap(~embryo, ncol = 4) +
    scale_color_manual(values = hue_pal()(28)[c(19, 7, 21, 9, 23, 11)]) +
    labs(title = "Late Bud, Nipbl FIN/+", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
    guides(color = guide_legend(override.aes = list(size = 2.3))) +
    theme_classic(base_size = 7) +
    theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"), strip.background = element_blank())

filename.png <- paste0(dir.name, "/projected-umap-facet-embryo-late-bud-fin-", i, "-projected-flox-", i, "-res-", res[i], ".png")
ggsave(plot = embryo.umap, filename = filename.png, device = "png", width = 6.5, height = 3.6)

embryo.umap <- ggplot() +
geom_point(data = sample(subclust.umap %>% filter(stage == "CC")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
    scale_color_manual(values = hue_pal()(28)[c(20, 8, 22, 10, 24, 12, 26, 14)]) +
    labs(title = "Cardiac Crescent, Nipbl FIN/+", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
    guides(color = guide_legend(override.aes = list(size = 2.3))) +
    theme_classic(base_size = 7) +
    theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"))

filename.png <- paste0(dir.name, "/projected-umap-by-embryo-cardiac-crescent-fin-", i, "-projected-flox-", i, "-res-", res[i], ".png")
ggsave(plot = embryo.umap, filename = filename.png, device = "png", width = 3.5, height = 2.25)

embryo.umap <- ggplot() +
geom_point(data = sample(subclust.umap %>% filter(stage == "CC")), mapping = aes(x = umap.1, y = umap.2, color = embryo), shape = 20, stroke = 0, size = 0.5) +
    facet_wrap(~embryo, ncol = 4) +
    scale_color_manual(values = hue_pal()(28)[c(20, 8, 22, 10, 24, 12, 26, 14)]) +
    labs(title = "Cardiac Crescent, Nipbl FIN/+", x = "UMAP 1", y = "UMAP 2", color = "Embryo") +
    guides(color = guide_legend(override.aes = list(size = 2.3))) +
    theme_classic(base_size = 7) +
    theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5), legend.key.size = unit(7, "pt"), strip.background = element_blank())

filename.png <- paste0(dir.name, "/projected-umap-facet-embryo-cardiac-crescent-fin-", i, "-projected-flox-", i, "-res-", res[i], ".png")
ggsave(plot = embryo.umap, filename = filename.png, device = "png", width = 6.5, height = 3.6)

whole.label <- subclust.umap %>% group_by(cluster.subclust.fin) %>% summarize(umap.1 = median(umap.1), umap.2 = median(umap.2))

cluster.umap <- ggplot() +
  geom_point(data = sample(subclust.umap), mapping = aes(x = umap.1, y = umap.2, color = cluster.subclust.fin), shape = 20, stroke = 0, size = 0.5) +
  geom_text(data = whole.label, mapping = aes(x = umap.1, y = umap.2, label = cluster.subclust.fin), size = 2.3) +
  labs(title = "Nipbl FIN/+", x = "UMAP 1", y = "UMAP 2", color = "Nipbl FIN/+\nCluster") +
  guides(color = guide_legend(override.aes = list(size = 2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5, size = 7), legend.key.size = unit(7, "pt"))
cluster.umap

filename.png <- paste0(dir.name, "/projected-umap-by-fin-fin-", i, "-projected-flox-", i, "-res-", res[i], ".png")
ggsave(plot = cluster.umap, filename = filename.png, device = "png", width = 3.5, height = 2.25, units = "in")

whole.label <- subclust.umap %>% group_by(cluster.subclust.flox) %>% summarize(umap.1 = median(umap.1), umap.2 = median(umap.2))

cluster.umap <- ggplot() +
  geom_point(data = sample(subclust.umap), mapping = aes(x = umap.1, y = umap.2, color = cluster.subclust.flox), shape = 20, stroke = 0, size = 0.5) +
  geom_text(data = whole.label, mapping = aes(x = umap.1, y = umap.2, label = cluster.subclust.flox), size = 2.3) +
  labs(title = "Nipbl FIN/+", x = "UMAP 1", y = "UMAP 2", color = "Nipbl Flox/+\nCluster") +
  guides(color = guide_legend(override.aes = list(size = 2.3))) +
  theme_classic(base_size = 7) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5, size = 7), legend.key.size = unit(7, "pt"))
cluster.umap

filename.png <- paste0(dir.name, "/projected-umap-by-flox-fin-", i, "-projected-flox-", i, "-res-", res[i], ".png")
ggsave(plot = cluster.umap, filename = filename.png, device = "png", width = 3.5, height = 2.25, units = "in")

print("loading fin projected")
filename.robj <- paste0(dir.name, "/fin-", i, "-projected-flox-", i, "-res-", res[i], ".Robj")
load(file = filename.robj)

print("loading DEGs")
filename.robj <- paste0(dir.name, "/projected-diff-genes-fin-", i, "-projected-flox-", i, "-res-", res[i], ".Robj")
load(file = filename.robj)

top.genes <- diff.genes %>% group_by(cluster) %>% slice_head(n = 79/length(levels(fin.subclust$cluster.subclust.flox)))

print("generating assay names")
n <- str_replace_all(i,"[.]","_")
sct.assay.name <- paste0("SCT_", n)

heatmap <- DoHeatmap(fin.subclust, assay = sct.assay.name, slot = "scale.data", features = as.vector(top.genes$gene), group.by = "ident", group.bar = TRUE, label = TRUE, size = 2.3, angle = 0, hjust = 0.5, draw.lines = TRUE) +
  scale_fill_gradientn(colors = rev(brewer.pal(n=5, name = "RdBu")), na.value = "white") +
  scale_x_discrete(position = "top") +
  labs(title = "Nipbl FIN/+", x = "Nipbl Flox/+ Cluster", y = "Top Genes", fill = "Standardized\nLog1p UMI") +
  guides(color = FALSE) +
  theme(axis.title = element_text(size = 7), axis.text = element_text(size = 7), plot.title = element_text(hjust = 0.5, size = 7), legend.title = element_text(size = 7), legend.text = element_text(size = 7), legend.key.size = unit(7, "pt"))

filename.png <- paste0(dir.name, "/heatmap-diff-genes-fin-", i, "-projected-flox-", i, "-res-", res[i], ".png")
ggsave(plot = heatmap, filename = filename.png, device = "png", units = "in", width = 6.5, height = 9)

}

```

```{bash}
scp -r /Volumes/all_ssd/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-1-projected-flox-1-res-0.074/fin-1.3-projected-flox-1.3-res-0.056/*.png schea2@hpc3.rcic.uci.edu:'/share/crsp/lab/alcalof/schea2/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-1-projected-flox-1-res-0.074/fin-1.3-projected-flox-1.3-res-0.056'

scp -r /Volumes/all_ssd/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-1-projected-flox-1-res-0.074/fin-1.2-projected-flox-1.2-res-0.104/*.png schea2@hpc3.rcic.uci.edu:'/share/crsp/lab/alcalof/schea2/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-1-projected-flox-1-res-0.074/fin-1.2-projected-flox-1.2-res-0.104'

scp -r /Volumes/all_ssd/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-1-projected-flox-1-res-0.074/fin-1.1-projected-flox-1.1-res-0.177/*.png schea2@hpc3.rcic.uci.edu:'/share/crsp/lab/alcalof/schea2/20220414-seurat/fin-integr-projected-flox-integr-res-0.0120/fin-1-projected-flox-1-res-0.074/fin-1.1-projected-flox-1.1-res-0.177'
```

