---
title: "Generate heatmap of top markers among whole"
output: html_notebook
---

Load libraries.
```{r}
library(Seurat)
library(tidyverse)
library(RColorBrewer)
```

Load Flox cells.
```{r}
load("/Volumes/Bud_SSD/20210505-seurat/flox-integr-neighbors.Robj")
```

Load cell identities. 
```{r}
load("/Volumes/Bud_SSD/20210505-seurat/flox-integr-clust-5/cluster-per-cell-flox-integr-clust-5.Robj")
```

Set cell identities. 
```{r}
flox.integr$wildtype.whole <- flox.integr.active.ident
Idents(flox.integr) <- flox.integr.active.ident
```

Load markers.
```{r}
load("/Volumes/Bud_SSD/20210505-seurat/flox-integr-clust-5/marker-genes-flox-integr-clust-5.Robj")
```

Factor gene. 
```{r}
marker.genes$gene <- factor(marker.genes$gene)
```

Grab top twenty genes per cluster. 
```{r}
marker.genes <- marker.genes %>% group_by(cluster) %>% slice_max(myAUC, n = 71/5)
marker.genes
```

Plot heatmap.
```{r}
heatmap <- DoHeatmap(flox.integr, assay = "SCT_GENOTYPE", slot = "data", features = as.vector(marker.genes$gene), group.by = "ident", group.bar = TRUE, label = TRUE, size = 2.3, angle = 0, hjust = 0.5, draw.lines = TRUE) +
scale_fill_viridis_c(na.value = "white") +
scale_x_discrete(position = "top") +
labs(title = "Whole, Nipbl Flox/+", fill = "Norm\nUMI") +
guides(color = "none") +
theme(axis.title = element_text(size = 7), axis.text = element_text(size = 7), plot.title = element_text(hjust = 0.5, size = 7), legend.title = element_text(size = 7), legend.text = element_text(size = 7), legend.key.size = unit(7, "pt"))

heatmap
```

Save heatmap.
```{r}
ggsave(plot = heatmap, filename = "/Volumes/Bud_SSD/20210505-seurat/flox-integr-clust-5/heatmap-marker-genes-flox-integr-clust-5.png", device = "png", units = "in", width = 6.5, height = 9)
```

