---
title: "What does the expression of gene diff-genes for each cluster look like?"
output: html_notebook
---

Load libraries.
```{r}
library(Seurat)
library(tidyverse)
library(RColorBrewer)
```

Load Flox cells.
```{r}
load("/Volumes/Bud_SSD/20210505-seurat/flox-integr-neighbors.Robj")
```

Load cell identities. 
```{r}
load("/Volumes/Bud_SSD/20210505-seurat/flox-integr-clust-5/cluster-per-cell-flox-integr-clust-5-18.Robj")
```

```{r}
flox.integr.active.ident <- recode(flox.integr.active.ident, 
                                                                                              "W1.1.1" = "EP",
                                                         "W1.1.2" = "NEP",
                                                         "W1.1.3" = "SE",
                                                         "W3.3" = "XEct",
                                                                                              "W1.2" = "NMP", 
                                                           "W2.1.1.1" = "MMP", 
                                                           "W2.1.1.2" = "PMP", 
                                                           "W2.1.1.3" = "PGC", 
                                                           "W2.1.2.1" = "SHF", 
                                                           "W2.1.2.2" = "TPM",
                                                         "W2.1.2.3" = "HPM", 
                                                           "W2.2.1" = "FHF2", 
                                                         "W2.2.2" = "FHF1", 
                                                           "W4.1" = "HMB", 
                                                           "W4.2" = "PE", 
                                                           "W5" = "PN",
                                                                                              "W3.1" = "XEnd",
                                                         "W3.2" = "DEP")
```


Set cell identities. 
```{r}
flox.integr$wildtype.whole <- flox.integr.active.ident
Idents(flox.integr) <- flox.integr.active.ident
```

Load diff-genes.
```{r}
diff.genes <- read.csv("/Volumes/Bud_SSD/20210505-seurat/flox-integr-clust-5/diff-genes-annotated-flox-integr-clust-5-18.csv")
head(diff.genes)
```

Factor gene. 
```{r}
diff.genes$gene <- factor(diff.genes$gene)
```

Grab top twenty genes per cluster. 
```{r}
diff.genes %>% group_by(cluster) %>% slice_head(n = 20)
target.genes <- diff.genes %>% group_by(cluster) %>% slice_head(n = 20) %>% pull(gene)
```

Pull expression data for cluster.
```{r}
#grab expression data for each gene
expr.umap <- as.data.frame(t(as.data.frame(flox.integr@assays$SCT_GENOTYPE@data[target.genes, ])))

colnames(expr.umap) <- str_replace_all(colnames(expr.umap), pattern = "-", replacement = ".")

expr.umap <- bind_cols(expr.umap, as.data.frame(flox.integr@reductions$umap@cell.embeddings))
#change all dashes to periods

#add names for each gene as cluster identity
target.clusters <- diff.genes %>% group_by(cluster) %>% slice_head(n = 20) %>% pull(cluster)
names(target.clusters) <- colnames(expr.umap)[1:length(target.genes)]
```


```{r}
dir.create("/Volumes/Bud_SSD/20210505-seurat/flox-integr-clust-5/feat-plot-top-diff-genes")

loop.count = 0

for (i in 1:length(target.genes)) {
  
loop.count = loop.count + 1

if(loop.count < 10) {
  string.loop.count <- paste0("00", loop.count)
} else if(loop.count >= 10 & loop.count < 100) {
    string.loop.count <- paste0("0", loop.count)
} else if(loop.count >= 100) {
  string.loop.count <- loop.count
}

feat.plot <- ggplot(data = expr.umap %>% arrange(colnames(expr.umap)[i]), mapping = aes(x = UMAP_1, y = UMAP_2)) +
         geom_point(mapping = aes_string(color = colnames(expr.umap)[i]), size = 0.1) +
        scale_color_gradient(low = "grey", high = "red", na.value = "grey") +
    labs(title = target.genes[i], subtitle = "Whole, Nipbl Flox/+", x = "UMAP 1", y = "UMAP 2", color = "Norm\nUMI") +
  theme_classic(base_size = 7) +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5), axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), legend.key.size = unit(7, "pt"))

filename.png <- paste0("/Volumes/Bud_SSD/20210505-seurat/flox-integr-clust-5/feat-plot-top-diff-genes/", target.clusters[i], "-", string.loop.count, "-", target.genes[i], "-feat-plot-flox-whole.png")
ggsave(plot = feat.plot, filename = filename.png, device = "png", unit = "in", width = 6.5, height = 4.5)

}
```
