---
title: "Where do all the clusters map in the whole embryo?"
output: html_notebook
---

```{r}
library(Seurat)
library(tidyverse)
library(RColorBrewer)
```

Load umap whole.
```{r}
load("/Volumes/Bud_SSD/20210505-seurat/fin-integr-clust-6/umap-by-cluster-fin-integr-clust-6.Robj")
whole.umap$mutant.whole <- as.character(as.vector(whole.umap$mutant.whole))
head(whole.umap)
table(whole.umap$mutant.whole)
```

Load umap cluster.
```{r}
load("/Volumes/Bud_SSD/20210505-seurat/fin-integr-clust-6/fin-M1-clust-2/umap-by-cluster-fin-M1-clust-2-3.Robj")
m1.umap <- clust.umap
table(m1.umap$mutant.clust)

load("/Volumes/Bud_SSD/20210505-seurat/fin-integr-clust-6/fin-M2-clust-3/umap-by-cluster-fin-M2-clust-3-9.Robj")
m2.umap <- clust.umap
table(m2.umap$mutant.clust)

load("/Volumes/Bud_SSD/20210505-seurat/fin-integr-clust-6/fin-M4-clust-2/umap-by-cluster-fin-M4-clust-2.Robj")
m4.umap <- clust.umap
table(m4.umap$mutant.clust)

```

Recode M2 cluster into subclusters.
```{r}
whole.umap[as.vector(rownames(m1.umap %>% filter(mutant.clust == "M1.1"))), "mutant.whole"] <- "M1.1"
whole.umap[as.vector(rownames(m1.umap %>% filter(mutant.clust == "M1.2.1"))), "mutant.whole"] <- "M1.2.1"
whole.umap[as.vector(rownames(m1.umap %>% filter(mutant.clust == "M1.2.2"))), "mutant.whole"] <- "M1.2.2"

whole.umap[as.vector(rownames(m2.umap %>% filter(mutant.clust == "M2.1.1.1"))), "mutant.whole"] <- "M2.1.1.1"
whole.umap[as.vector(rownames(m2.umap %>% filter(mutant.clust == "M2.1.1.2"))), "mutant.whole"] <- "M2.1.1.2"
whole.umap[as.vector(rownames(m2.umap %>% filter(mutant.clust == "M2.1.1.3"))), "mutant.whole"] <- "M2.1.1.3"
whole.umap[as.vector(rownames(m2.umap %>% filter(mutant.clust == "M2.1.1.4"))), "mutant.whole"] <- "M2.1.1.4"
whole.umap[as.vector(rownames(m2.umap %>% filter(mutant.clust == "M2.1.2"))), "mutant.whole"] <- "M2.1.2"
whole.umap[as.vector(rownames(m2.umap %>% filter(mutant.clust == "M2.2.1"))), "mutant.whole"] <- "M2.2.1"
whole.umap[as.vector(rownames(m2.umap %>% filter(mutant.clust == "M2.2.2"))), "mutant.whole"] <- "M2.2.2"
whole.umap[as.vector(rownames(m2.umap %>% filter(mutant.clust == "M2.2.3"))), "mutant.whole"] <- "M2.2.3"
whole.umap[as.vector(rownames(m2.umap %>% filter(mutant.clust == "M2.3"))), "mutant.whole"] <- "M2.3"

whole.umap[as.vector(rownames(m4.umap %>% filter(mutant.clust == "M4.1"))), "mutant.whole"] <- "M4.1"
whole.umap[as.vector(rownames(m4.umap %>% filter(mutant.clust == "M4.2"))), "mutant.whole"] <- "M4.2"

whole.umap$mutant.whole <- factor(whole.umap$mutant.whole, levels = c("M1.1", "M1.2.1", "M1.2.2", "M2.1.1.1", "M2.1.1.2", "M2.1.1.3", "M2.1.1.4", "M2.1.2", "M2.2.1", "M2.2.2", "M2.2.3", "M2.3", "M3", "M4.1", "M4.2", "M5", "M6"))

table(whole.umap$mutant.whole)
```

```{r}
save(whole.umap, file = "/Volumes/Bud_SSD/20210505-seurat/fin-integr-clust-6/umap-by-cluster-fin-integr-clust-6-17.Robj")
```

Generate label umap.
```{r}
whole.label <- whole.umap %>% group_by(mutant.whole) %>% summarize(umap.1 = median(umap.1), umap.2 = median(umap.2))
```

Generate cluster umap.
```{r}
cluster.umap <- ggplot() +
geom_point(data = sample(whole.umap), mapping = aes(x = umap.1, y = umap.2, color = mutant.whole), size = 0.1) +
geom_text(data = whole.label, mapping = aes(x = umap.1, y = umap.2, label = mutant.whole), size = 3.5) +
labs(title = "Whole, Nipbl FIN/+", x = "UMAP 1", y = "UMAP 2", color = "Cluster") +
  guides(color = guide_legend(override.aes = list(size = 2.3))) +
theme_classic(base_size = 7) +
theme(axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), plot.title = element_text(hjust = 0.5, size = 7), legend.key.size = unit(7, "pt"))

cluster.umap
```

```{r}
ggsave(plot = cluster.umap, filename = "/Volumes/Bud_SSD/20210505-seurat/fin-integr-clust-6/umap-by-cluster-fin-integr-clust-6-17.png", device = "png", width = 6.5, height = 4.5, units = "in")
```

Upload files onto hpc3.
```{bash}
scp /Volumes/Bud_SSD/20210505-seurat/fin-integr-clust-6/umap-by-cluster-fin-integr-clust-6-17.png schea2@hpc3.rcic.uci.edu:/dfs6/pub/schea2/20210505-seurat/fin-integr-clust-6

scp /Volumes/Bud_SSD/20210505-seurat/fin-integr-clust-6/umap-by-cluster-fin-integr-clust-6-17.Robj schea2@hpc3.rcic.uci.edu:/dfs6/pub/schea2/20210505-seurat/fin-integr-clust-6

```
